### ISSUE TITLE
Is this repository still open for contribution?

### ISSUE THREAD

**Issue by pandevim** [mrpandey/particleAnimation#1]
@mrpandey I'm just having a look and there's something bothers me. Can I mention that?

**Comment by mrpandey** [comment]
Yup, sure.

**Comment by pandevim** [comment]
Actually there's not whole lot of a change and tell me if I'm wrong: in [#L22](https://github.com/mrpandey/particleAnimation/blob/2ac2079bbdf38a2a3500cfb331043c220ba158bc/Particle.h#L22) you've given the *label* `public` which specifies the below to be in `public` scope. But in `struct` the de-facto scope is `public` so maybe in [#L8](https://github.com/mrpandey/particleAnimation/blob/2ac2079bbdf38a2a3500cfb331043c220ba158bc/Particle.h#L8) `class` keyword is intended?
Indeed this is not a bug just something I thought worth attention or maybe not. @mrpandey great app by the way!
https://github.com/mrpandey/particleAnimation/blob/2ac2079bbdf38a2a3500cfb331043c220ba158bc/Particle.h#L8-L26

**Comment by mrpandey** [comment]
Thanks for pointing out. I realized I was using `class` in every other file, but `struct` in `Particle.h`.
So for consistency, I changed the `struct` to `class` and made entire class `public`.
